### ISSUE TITLE
developing of contact-us and about-us page and other pages for bettr user interaction and user engagement 

### ISSUE THREAD

**Issue by dhruv-4444** [Artemiskgg1/NexaSite#1]
hey @Artemiskgg1 i will able to help you enhancing the ui for contact us page, about-us page and other page for better user engagement and will also make that responsive so that user can access it from any device.
assign me this task, with hacktoberfest labels.
Thanks in Advance

**Comment by Artemiskgg1** [comment]
Thank you for connecting!
This repository is focused on the development of a company website. Please design it to align with the current theme and ensure it has a professional, corporate appearance. 
Please continue any further discussions in the repository's Discussions tab.
