### ISSUE TITLE
About Us and Product and Services in Mobile(hacktoberfest)

### ISSUE THREAD

**Issue by MARKASCHARAN** [Artemiskgg1/NexaSite#47]
I can make this website main page mobile responsive and small devices fit, assign it me

<img width="1470" alt="Screenshot 2024-10-18 at 3 06 17 AM" src="https://github.com/user-attachments/assets/d3de1c8d-acc0-44d5-b33d-266653cb8237">
<img width="1470" alt="Screenshot 2024-10-18 at 3 06 37 AM" src="https://github.com/user-attachments/assets/b7192434-260c-4c4d-93f5-e53c56b8aa66">

**Comment by Artemiskgg1** [comment]
@MARKASCHARAN This issue is already assigned to someone else .
#7
